// Verified simple-icons slugs (HTTP-probed against cdn.simpleicons.org).
// Returns null for files with no known logo — caller falls back to a generic icon.

const FILENAME_SLUGS: Record<string, string | null> = {
  "package.json": "npm",
  "package-lock.json": "npm",
  "pnpm-lock.yaml": "pnpm",
  "yarn.lock": "yarn",
  "go.mod": "go",
  "go.sum": "go",
  "Cargo.toml": "rust",
  "Cargo.lock": "rust",
  "pyproject.toml": "python",
  "requirements.txt": "pypi",
  Pipfile: "python",
  "Pipfile.lock": "python",
  Gemfile: "rubygems",
  "Gemfile.lock": "rubygems",
  "composer.json": "composer",
  "composer.lock": "composer",
  Dockerfile: "docker",
  "docker-compose.yml": "docker",
  "docker-compose.yaml": "docker",
  "tsconfig.json": "typescript",
  "vite.config.ts": "vite",
  "vite.config.js": "vite",
  "webpack.config.js": "webpack",
  "rollup.config.js": "rollupdotjs",
  "esbuild.config.js": "esbuild",
  "next.config.js": "nextdotjs",
  "next.config.ts": "nextdotjs",
  "nuxt.config.ts": "nuxt",
  "tailwind.config.js": "tailwindcss",
  "tailwind.config.ts": "tailwindcss",
  "svelte.config.js": "svelte",
  "angular.json": "angular",
  "eslint.config.js": "eslint",
  "eslint.config.mjs": "eslint",
  ".eslintrc.js": "eslint",
  ".eslintrc.json": "eslint",
  ".prettierrc": "prettier",
  ".prettierrc.json": "prettier",
  "prettier.config.js": "prettier",
  "ruff.toml": "ruff",
  "jest.config.js": "jest",
  "jest.config.ts": "jest",
  "vitest.config.ts": "vitest",
  Makefile: "make",
  "README.md": "markdown",
  "CHANGELOG.md": "markdown",
};

const EXTENSION_SLUGS: Record<string, string> = {
  ts: "typescript",
  tsx: "typescript",
  js: "javascript",
  jsx: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  py: "python",
  go: "go",
  rs: "rust",
  rb: "ruby",
  kt: "kotlin",
  swift: "swift",
  cpp: "cplusplus",
  cxx: "cplusplus",
  cc: "cplusplus",
  hpp: "cplusplus",
  c: "c",
  h: "c",
  php: "php",
  dart: "dart",
  lua: "lua",
  pl: "perl",
  scala: "scala",
  ex: "elixir",
  exs: "elixir",
  hs: "haskell",
  html: "html5",
  htm: "html5",
  css: "css",
  vue: "vuedotjs",
  svelte: "svelte",
  md: "markdown",
  markdown: "markdown",
  json: "json",
  yaml: "yaml",
  yml: "yaml",
  toml: "toml",
  sh: "shell",
  zsh: "shell",
};

export function fileIconSlug(filename: string): string | null {
  if (filename in FILENAME_SLUGS) return FILENAME_SLUGS[filename];
  const dot = filename.lastIndexOf(".");
  if (dot < 0) return null;
  const ext = filename.slice(dot + 1).toLowerCase();
  return EXTENSION_SLUGS[ext] ?? null;
}
